'use strict';

module.exports = {
  WALLET_CREATED: 'WALLET_CREATED',
  WALLET_FUNDED: 'WALLET_FUNDED',
  WALLET_WITHDRAWN: 'WALLET_WITHDRAWN',
  WALLET_PAYMENT_PROCESSED: 'WALLET_PAYMENT_PROCESSED',
  WALLET_REWARD_CREDITED: 'WALLET_REWARD_CREDITED',
};