'use strict';

module.exports = {
  PARTY_INVITE_SENT: 'PARTY_INVITE_SENT',
  PARTY_STATUS_UPDATED: 'PARTY_STATUS_UPDATED',
  PARTY_MEMBER_REMOVED: 'PARTY_MEMBER_REMOVED',
  BILL_SPLIT_REQUESTED: 'BILL_SPLIT_REQUESTED',
};