// socket/events/customer/mtables/paymentRequestEvents.js
'use strict';

module.exports = {
  BILL_SPLIT_REQUEST_SENT: 'BILL_SPLIT_REQUEST_SENT',
  BILL_SPLIT_REQUEST_SUCCESS: 'BILL_SPLIT_REQUEST_SUCCESS',
  BILL_SPLIT_REQUEST_ERROR: 'BILL_SPLIT_REQUEST_ERROR',
  PRE_ORDER_BILL_SPLIT_REQUEST_SENT: 'PRE_ORDER_BILL_SPLIT_REQUEST_SENT',
  PRE_ORDER_BILL_SPLIT_REQUEST_SUCCESS: 'PRE_ORDER_BILL_SPLIT_REQUEST_SUCCESS',
  PRE_ORDER_BILL_SPLIT_REQUEST_ERROR: 'PRE_ORDER_BILL_SPLIT_REQUEST_ERROR',
};