'use strict';

module.exports = {
  GAMIFICATION_ACTIONS: {
    mtables: [
      { action: 'order_placed', name: 'Order Placed', points: 15, walletCredit: null },
      { action: 'order_review_submitted', name: 'Order Review Submitted', points: 10, walletCredit: null },
      { action: 'booking_created', name: 'Booking Created', points: 10, walletCredit: null },
      { action: 'check_in', name: 'Checked In', points: 5, walletCredit: null },
      { action: 'pre_order_placed', name: 'Pre-Order Placed', points: 8, walletCredit: null },
      { action: 'table_searched', name: 'Table Searched', points: 2, walletCredit: null },
      { action: 'party_member_invited', name: 'Party Member Invited', points: 5, walletCredit: null },
      { action: 'party_member_status_updated', name: 'Party Member Status Updated', points: 3, walletCredit: null },
      { action: 'party_member_removed', name: 'Party Member Removed', points: 2, walletCredit: null },
      { action: 'bill_split_initiated', name: 'Bill Split Initiated', points: 10, walletCredit: null },
      { action: 'create_pre_order', name: 'Create Pre-Order', points: 12, walletCredit: null },
      { action: 'initiate_bill_split', name: 'Initiate Bill Split', points: 15, walletCredit: null },
    ],
    munch: [
      { action: 'add_to_cart', name: 'Add to Cart', points: 5, walletCredit: null },
      { action: 'order_placed', name: 'Order Placed', points: 15, walletCredit: null },
      { action: 'dietary_filter_applied', name: 'Dietary Filter Applied', points: 5, walletCredit: null },
      { action: 'order_cancelled', name: 'Order Cancelled', points: 5, walletCredit: null },
      { action: 'feedback_requested', name: 'Feedback Requested', points: 10, walletCredit: null },
    ],
    mtxi: [
      { action: 'ride_requested', name: 'Ride Requested', points: 12, walletCredit: null },
      { action: 'shared_ride_requested', name: 'Shared Ride Requested', points: 15, walletCredit: null },
      { action: 'ride_review_submitted', name: 'Ride Review Submitted', points: 10, walletCredit: null },
    ],
    mevents: [
      { action: 'event_created', name: 'Event Created', points: 50, walletCredit: null },
      { action: 'event_participant_added', name: 'Event Participant Added', points: 5, walletCredit: null },
      { action: 'event_review_submitted', name: 'Event Review Submitted', points: 15, walletCredit: null },
      { action: 'event_live_update_shared', name: 'Event Live Update Shared', points: 10, walletCredit: null },
    ],
    mpark: [
      { action: 'parking_booked', name: 'Parking Booked', points: 10, walletCredit: null },
      { action: 'parking_check_in', name: 'Parking Checked In', points: 5, walletCredit: null },
      { action: 'parking_time_extended', name: 'Parking Time Extended', points: 3, walletCredit: null },
      { action: 'accessible_parking_booked', name: 'Accessible Parking Booked', points: 15, walletCredit: null },
    ],
    analytics: [
      { action: 'behavior_tracked', name: 'Behavior Tracked', points: 10, walletCredit: null },
      { action: 'spending_analyzed', name: 'Spending Analyzed', points: 10, walletCredit: null },
      { action: 'recommendations_received', name: 'Recommendations Received', points: 10, walletCredit: null },
      { action: 'parking_behavior_tracked', name: 'Parking Behavior Tracked', points: 10, walletCredit: null },
    ],
    social: [
      { action: 'friend_request_sent', name: 'Friend Request Sent', points: 3, walletCredit: null },
      { action: 'friend_request_accepted', name: 'Friend Request Accepted', points: 5, walletCredit: null },
      { action: 'group_chat_message', name: 'Group Chat Message Sent', points: 2, walletCredit: null },
      { action: 'split_payment_initiated', name: 'Split Payment Initiated', points: 10, walletCredit: null },
      { action: 'social_post_shared', name: 'Social Post Shared', points: 8, walletCredit: null },
      { action: 'referral_sent', name: 'Referral Sent', points: 20, walletCredit: null },
    ],
    general: [
      { action: 'profile_completed', name: 'Profile Completed', points: 10, walletCredit: null },
      { action: 'feedback_submitted', name: 'Feedback Submitted', points: 8, walletCredit: null },
      { action: 'tipping', name: 'Tip Provided', points: 5, walletCredit: null },
      { action: 'subscription_enrolled', name: 'Subscription Enrolled', points: 15, walletCredit: null },
      { action: 'subscription_managed', name: 'Subscription Managed', points: 5, walletCredit: null },
      { action: 'support_interaction', name: 'Support Interaction', points: 5, walletCredit: null },
    ],
    dispute: [
      { action: 'dispute_created', name: 'Dispute Created', points: 5, walletCredit: null },
      { action: 'dispute_resolved', name: 'Dispute Resolved', points: 10, walletCredit: null },
      { action: 'parking_dispute_cancelled', name: 'Parking Dispute Cancelled', points: 3, walletCredit: null },
    ],
    profile: [
      { action: 'profile_updated', name: 'Profile Updated', points: 5, walletCredit: null },
      { action: 'accessibility_settings_updated', name: 'Accessibility Settings Updated', points: 5, walletCredit: null },
      { action: 'privacy_settings_updated', name: 'Privacy Settings Updated', points: 5, walletCredit: null },
      { action: 'country_set', name: 'Country Set', points: 3, walletCredit: null },
      { action: 'language_set', name: 'Language Set', points: 3, walletCredit: null },
      { action: 'dietary_preferences_set', name: 'Dietary Preferences Set', points: 5, walletCredit: null },
      { action: 'default_address_set', name: 'Default Address Set', points: 5, walletCredit: null },
    ],
    reviews: [
      { action: 'merchant_review_submitted', name: 'Merchant Review Submitted', points: 10, walletCredit: null },
      { action: 'staff_review_submitted', name: 'Staff Review Submitted', points: 8, walletCredit: null },
      { action: 'driver_review_submitted', name: 'Driver Review Submitted', points: 8, walletCredit: null },
      { action: 'review_comment_added', name: 'Review Comment Added', points: 5, walletCredit: null },
      { action: 'review_upvoted', name: 'Review Upvoted', points: 3, walletCredit: null },
    ],
    tip: [
      { action: 'tip_ride', name: 'Tipped for Ride', points: 5, walletCredit: null },
      { action: 'tip_order', name: 'Tipped for Order', points: 5, walletCredit: null },
      { action: 'tip_booking', name: 'Tipped for Booking', points: 5, walletCredit: null },
      { action: 'tip_event_service', name: 'Tipped for Event Service', points: 5, walletCredit: null },
      { action: 'tip_in_dining_order', name: 'Tipped for In-Dining Order', points: 5, walletCredit: null },
      { action: 'tip_parking_booking', name: 'Tipped for Parking Booking', points: 5, walletCredit: null },
    ],
    wallet: [
      { action: 'ADD_FUNDS', name: 'Funds Added to Wallet', points: 10, walletCredit: null },
      { action: 'ORDER_PAYMENT', name: 'Payment with Wallet', points: 15, walletCredit: null },
    ],
    crossVerticalOutlook: [
      { action: 'services_viewed', name: 'Services Viewed', points: 5, walletCredit: null },
      { action: 'service_cancelled', name: 'Service Cancelled', points: 3, walletCredit: null },
      { action: 'service_status_checked', name: 'Service Status Checked', points: 2, walletCredit: null },
    ],
  },
  GAMIFICATION_SETTINGS: {
    MAX_DAILY_ACTIONS: 50,
    POINTS_EXPIRY_DAYS: 365,
    LEADERBOARD_TYPES: ['global', 'regional', 'friends'],
    REWARD_CATEGORIES: ['discounts', 'free_services', 'crypto_rewards', 'exclusive_access'],
    AI_PERSONALIZATION: true,
  },
  ERROR_CODES: ['INVALID_ACTION', 'MAX_ACTIONS_EXCEEDED', 'INVALID_REWARD'],
  SUCCESS_MESSAGES: ['ACTION_RECORDED', 'POINTS_AWARDED', 'REWARD_REDEEMED'],
  ACHIEVEMENT_TYPES: [
    {
      id: 'first_order',
      name: 'First Order',
      criteria: { action: 'order_placed', count: 1 },
    },
    {
      id: 'loyal_customer',
      name: 'Loyal Customer',
      criteria: { action: 'order_placed', count: 10 },
    },
    {
      id: 'feedback_guru',
      name: 'Feedback Guru',
      criteria: { action: 'feedback_requested', count: 5 },
    },
    {
      id: 'review_contributor',
      name: 'Review Contributor',
      criteria: { action: 'merchant_review_submitted', count: 5 },
    },
  ],
};