'use strict';

module.exports = {
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  COUNTRY_SET: 'COUNTRY_SET',
  LANGUAGE_SET: 'LANGUAGE_SET',
  DIETARY_PREFERENCES_SET: 'DIETARY_PREFERENCES_SET',
  DEFAULT_ADDRESS_SET: 'DEFAULT_ADDRESS_SET',
};