'use strict';

module.exports = {
  CUSTOMER_ACTIONS: [
    // Existing Actions
    { action: 'check_in', points: 20, walletCredit: 0.50 },
    { action: 'pre_order', points: 50, walletCredit: 1.00 },
    { action: 'group_coordinator', points: 100, walletCredit: 2.00 },
    { action: 'referral', points: 100, walletCredit: 2.00 },
    { action: 'review', points: 25, walletCredit: 0.60 },
    { action: 'event_planning', points: 100, walletCredit: 2.00 },
    { action: 'split_payment', points: 20, walletCredit: 0.50 },
    { action: 'subscription_loyalty', points: 200, walletCredit: 5.00 },
    { action: 'dispute_created', points: 10 },
    { action: 'dispute_resolved', points: 10 },
    { action: 'event_created', points: 10 },
    { action: 'event_participant_added', points: 10 },
    { action: 'event_services_added', points: 10 },
    { action: 'event_chat_enabled', points: 10 },
    { action: 'interaction_tracked', points: 5 },
    { action: 'high_engagement', points: 20 },
    { action: 'booking_added', points: 10 },
    { action: 'feedback_submitted', points: 10 },
    { action: 'order_placed', points: 10 },
    { action: 'pre_order_placed', points: 10 },
    { action: 'payment_completed', points: 10 },
    { action: 'promotion_redeemed', points: 15, walletCredit: 0.30 },
    { action: 'subscription_enrollment', points: 50, walletCredit: 1.00 },
    { action: 'tier_upgrade', points: 100, walletCredit: 2.00 },
    { action: 'subscription_cancellation', points: 10 },
    { action: 'support_interaction', points: 10, walletCredit: 0.20 },
    { action: 'ticket_closure', points: 5 },
    { action: 'promotion_cancellation', points: 5 },
    { action: 'delivery_tracked', points: 10, walletCredit: 0.20 },
    { action: 'delivery_cancellation', points: 5 },
    { action: 'inventory_updated', points: 10 },
    { action: 'order_cancellation', points: 5 },
    { action: 'cart_updated', points: 5, walletCredit: 0.10 },
    { action: 'merchant_browsed', points: 5 },
    { action: 'driver_communication', points: 5, walletCredit: 0.10 },
    { action: 'subscription_activity', points: 5, walletCredit: 0.10 },
    { action: 'payment_refunded', points: 15, walletCredit: 0.30 },
    { action: 'profile_updated', points: 50, walletCredit: 1.00 },
    { action: 'privacy_settings_updated', points: 30, walletCredit: 0.50 },
    { action: 'accessibility_updated', points: 30, walletCredit: 0.50 },
    { action: 'create_wallet', points: 50, walletCredit: 1.00 },
    { action: 'deposit_funds', points: 'dynamic', walletCredit: 0.20 }, // 5 points per currency unit
    { action: 'withdraw_funds', points: 20, walletCredit: 0.50 },
    { action: 'payment_with_wallet', points: 'dynamic', walletCredit: 0.30 }, // 3 points per currency unit
    { action: 'gamification_reward', points: 'dynamic', walletCredit: 0.40 }, // 10 points per currency unit
    { action: 'create_tip', points: 'dynamic', walletCredit: 0.20 }, // 10 points per currency unit
    { action: 'complete_tip', points: 50, walletCredit: 1.00 },
    { action: 'friend_request', points: 20, walletCredit: 0.50 },
    { action: 'friend_accepted', points: 30, walletCredit: 0.75 },
    { action: 'group_chat_message', points: 5, walletCredit: 0.10 },
    { action: 'create_post', points: 25, walletCredit: 0.60 },
    { action: 'post_reaction', points: 10, walletCredit: 0.20 },
    { action: 'share_story', points: 20, walletCredit: 0.50 },
    { action: 'service_invite', points: 30, walletCredit: 0.75 },
    { action: 'bill_split_initiated', points: 40, walletCredit: 1.00 },
    { action: 'submit_review', points: 25, walletCredit: 0.60 },
    { action: 'review_upvote', points: 10, walletCredit: 0.20 },
    { action: 'review_comment', points: 15, walletCredit: 0.30 },
  ],
  POINT_EXPIRY_DAYS: 365,
  MAX_POINTS_PER_DAY: 1000,
  ERROR_CODES: [
    'INVALID_USER',
    'INVALID_ACTION',
    'INSUFFICIENT_POINTS',
    'MAX_POINTS_EXCEEDED',
  ],
  SUCCESS_MESSAGES: [
    'Points awarded',
    'Reward redeemed',
  ],
};