'use strict';

module.exports = {
  EVENT_STATUSES: ['DRAFT', 'CONFIRMED', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'POSTPONED'],
  EVENT_OCCASIONS: [
    'BIRTHDAY', 'ANNIVERSARY', 'CORPORATE', 'SOCIAL', 'WEDDING', 'CONFERENCE',
    'BABY_SHOWER', 'GRADUATION', 'FESTIVAL', 'CHARITY', 'CONCERT', 'SPORTS', 'THEATER', 'OTHER'
  ],
  PAYMENT_TYPES: ['SOLO', 'SPLIT', 'SPONSOR', 'CROWDFUNDED'],
  PARTICIPANT_STATUSES: ['INVITED', 'ACCEPTED', 'DECLINED', 'CHECKED_IN', 'NO_SHOW'],
  EVENT_CONFIG: {
    MAX_PARTICIPANTS: 1000,
    MAX_SERVICES: 100,
    MAX_TITLE_LENGTH: 150,
    MAX_DESCRIPTION_LENGTH: 2000,
    MIN_LEAD_TIME_DAYS: 0.25,
    SUPPORTED_CITIES: {
      US: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami', 'San Francisco'],
      GB: ['London', 'Manchester', 'Birmingham', 'Glasgow', 'Edinburgh'],
      EU: ['Berlin', 'Paris', 'Amsterdam', 'Rome', 'Madrid'],
      CA: ['Toronto', 'Vancouver', 'Montreal', 'Calgary'],
      AU: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
      MW: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
      TZ: ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mwanza'],
      KE: ['Nairobi', 'Mombasa', 'Kisumu', 'Eldoret'],
      MZ: ['Maputo', 'Beira', 'Nampula', 'Matola'],
      ZA: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'],
      IN: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad'],
      CM: ['Douala', 'Yaoundé'],
      GH: ['Accra', 'Kumasi'],
      MX: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla'],
      ER: ['Asmara', 'Keren', 'Massawa']
    },
    SUPPORTED_CURRENCIES: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'MWK', 'TZS', 'KES', 'MZN', 'ZAR', 'INR', 'XAF', 'GHS', 'MXN', 'ERN'],
    ALLOWED_DIETARY_FILTERS: ['VEGETARIAN', 'VEGAN', 'GLUTEN_FREE', 'NUT_FREE', 'DAIRY_FREE', 'HALAL', 'KOSHER', 'LOW_CARB', 'ORGANIC'],
    SERVICE_INTEGRATIONS: ['MUNCH', 'MTXI', 'MTABLES', 'MPARK', 'MSTAYS', 'MTICKETS', 'EXTERNAL_VENDORS'],
    EVENT_TEMPLATES: [
      'BIRTHDAY_BASH', 'CORPORATE_MEETING', 'WEDDING', 'SOCIAL_GATHERING',
      'CONFERENCE', 'BABY_SHOWER', 'GRADUATION', 'FESTIVAL', 'CHARITY_EVENT',
      'CONCERT', 'SPORTS_EVENT', 'THEATER', 'CUSTOM'
    ],
    AI_PLANNING_TOOLS: [
      'budget_optimizer',
      'vendor_recommendations',
      'schedule_generator',
      'venue_suggestions',
      'guest_list_optimizer',
      'sustainability_scorer',
      'logistics_coordinator',
      'ticket_allocation_optimizer' 
    ],
    EVENT_BUNDLING: {
      ENABLED: true,
      BUNDLE_TYPES: [
        'DINING_TRANSPORT', 'STAY_VENUE', 'TICKET_STAY', 'TICKET_EVENT',
        'FULL_EVENT', 'CUSTOM'
      ],
      MAX_BUNDLED_SERVICES: 6,
      AI_BUNDLE_OPTIMIZATION: true
    },
    TICKET_INTEGRATION: {
      TICKET_TYPES: ['EVENT', 'FESTIVAL', 'CONCERT', 'SPORTS', 'THEATER'],
      ACCESS_METHODS: ['QR_CODE', 'BARCODE', 'DIGITAL_PASS', 'NFC'],
      MAX_TICKETS_PER_EVENT: 10000,
      TICKET_STATUSES: ['AVAILABLE', 'RESERVED', 'SOLD', 'USED', 'CANCELLED', 'REFUNDED'],
      AI_TICKET_ALLOCATION: true
    }
  },
  GROUP_CONFIG: {
    MAX_FRIENDS_PER_EVENT: 1000,
    INVITE_STATUSES: ['PENDING', 'ACCEPTED', 'DECLINED', 'REMOVED', 'WAITLISTED'],
    INVITE_METHODS: ['APP', 'SMS', 'EMAIL', 'WHATSAPP', 'TELEGRAM', 'QR_CODE'],
    BILL_SPLIT_TYPES: ['EQUAL', 'CUSTOM', 'PERCENTAGE', 'SPONSOR_CONTRIBUTION', 'CROWDFUNDED'],
    MAX_SPLIT_PARTICIPANTS: 100,
    GROUP_CHAT: ['in_app', 'whatsapp_integration', 'telegram_integration', 'real_time_updates'],
    SOCIAL_MEDIA_SHARING: ['event_invite', 'post_event', 'live_updates', 'tag_friends', 'crowdfunding_appeal', 'ticket_share'],
    GROUP_COORDINATION: {
      RSVP_DEADLINE_DAYS: 7,
      AI_ATTENDANCE_PREDICTION: true,
      GROUP_PREFERENCES: ['dietary', 'accessibility', 'transport', 'accommodation', 'ticket_type']
    }
  },
  VENDOR_COORDINATION: {
    VENDOR_TYPES: [
      'CATERING', 'TRANSPORT', 'VENUE', 'PARKING', 'ACCOMMODATION', 'ENTERTAINMENT',
      'DECOR', 'SECURITY', 'PHOTOGRAPHY', 'EVENT_PLANNING', 'TICKET_PROVIDER'
    ],
    VENDOR_STATUSES: ['PENDING', 'CONFIRMED', 'ACTIVE', 'COMPLETED', 'CANCELLED'],
    CONTRACT_TYPES: ['FIXED', 'HOURLY', 'PER_PERSON', 'PACKAGE'],
    AI_VENDOR_MATCHING: true,
    VENDOR_INTEGRATION: {
      CROSS_SERVICE_SYNC: ['MUNCH', 'MTXI', 'MTABLES', 'MPARK', 'MSTAYS', 'MTICKETS'],
      REAL_TIME_UPDATES: true
    }
  },
  TIPPING_CONSTANTS: {
    TIPPABLE_ROLES: ['staff', 'merchant'],
    TIP_METHODS: ['percentage', 'fixed_amount', 'custom'],
    TIP_STATUSES: ['pending', 'completed', 'failed', 'refunded'],
    TIP_SETTINGS: {
      MIN_TIP_AMOUNT: 1,
      MAX_TIP_AMOUNT: 200,
      DEFAULT_TIP_PERCENTAGES: [10, 15, 20],
      MAX_TIPS_PER_EVENT: 2,
      TIP_DISTRIBUTION: {
        staff: 'direct',
        merchant: 'pooled'
      },
      AUTO_TIP_SUGGESTION: true,
      TIP_CURRENCY: 'same_as_event',
      TRANSACTION_LIMIT_PER_DAY: 50
    }
  },
  ANALYTICS_CONFIG: {
    METRICS: [
      'PARTICIPANT_ENGAGEMENT', 'BUDGET_ADHERENCE', 'VENDOR_PERFORMANCE', 'EVENT_ATTENDANCE',
      'SOCIAL_MEDIA_IMPACT', 'SERVICE_UTILIZATION', 'SUSTAINABILITY_IMPACT', 'CROWDFUNDING_SUCCESS',
      'TICKET_SALES'
    ],
    REPORT_FORMATS: ['PDF', 'CSV', 'JSON', 'DASHBOARD'],
    DATA_RETENTION_DAYS: 730,
    PERFORMANCE_THRESHOLDS: {
      TARGET_ATTENDANCE_PERCENTAGE: 80,
      MAX_VENDOR_RESPONSE_TIME_HOURS: 4,
      MAX_TICKET_PROCESSING_TIME_MINUTES: 5
    }
  },
  NOTIFICATION_TYPES: {
    EVENT_CREATED: 'EVENT_CREATED',
    EVENT_INVITATION: 'EVENT_INVITATION',
    BILL_SPLIT_REQUEST: 'BILL_SPLIT_REQUEST',
    EVENT_CHAT_MESSAGE: 'EVENT_CHAT_MESSAGE',
    EVENT_UPDATED: 'EVENT_UPDATED',
    VENDOR_CONFIRMED: 'VENDOR_CONFIRMED',
    SOCIAL_MEDIA_POST: 'SOCIAL_MEDIA_POST',
    EVENT_LIVE_UPDATE: 'EVENT_LIVE_UPDATE',
    CROWDFUNDING_UPDATE: 'CROWDFUNDING_UPDATE',
    STAY_CONFIRMATION: 'STAY_CONFIRMATION',
    SERVICE_BUNDLE_CONFIRMED: 'SERVICE_BUNDLE_CONFIRMED',
    TICKET_CONFIRMATION: 'TICKET_CONFIRMATION',
    TICKET_UPCOMING: 'TICKET_UPCOMING'
  },
  AUDIT_TYPES: {
    EVENT_CREATED: 'EVENT_CREATED',
    BILL_PROCESSED: 'BILL_PROCESSED',
    CHAT_MESSAGE_SENT: 'CHAT_MESSAGE_SENT',
    EVENT_UPDATED: 'EVENT_UPDATED',
    PARTICIPANT_ADDED: 'PARTICIPANT_ADDED',
    VENDOR_COORDINATED: 'VENDOR_COORDINATED',
    SOCIAL_MEDIA_INTERACTION: 'SOCIAL_MEDIA_INTERACTION',
    CROWDFUNDING_PROCESSED: 'CROWDFUNDING_PROCESSED',
    SERVICE_BUNDLE_CREATED: 'SERVICE_BUNDLE_CREATED',
    TICKET_SOLD: 'TICKET_SOLD'
  },
  ERROR_TYPES: [
    'EVENT_NOT_FOUND', 'INVALID_CUSTOMER', 'INVALID_PARTICIPANT', 'INVALID_SERVICE', 'UNAUTHORIZED_EVENT',
    'MAX_PARTICIPANTS_EXCEEDED', 'MAX_SERVICES_EXCEEDED', 'INVALID_PAYMENT_TYPE', 'INSUFFICIENT_FUNDS',
    'BILL_SPLIT_FAILED', 'INVALID_EVENT', 'VENDOR_NOT_AVAILABLE', 'WALLET_INSUFFICIENT_FUNDS',
    'CROWDFUNDING_FAILED', 'INVALID_BUNDLE', 'STAY_NOT_AVAILABLE', 'TICKET_NOT_AVAILABLE'
  ],
  SUCCESS_MESSAGES: [
    'EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_CANCELLED', 'PARTICIPANT_ADDED', 'BILL_PROCESSED',
    'CHAT_ENABLED', 'VENDOR_CONFIRMED', 'SOCIAL_POST_SHARED', 'CROWDFUNDING_SUCCESS',
    'SERVICE_BUNDLE_CONFIRMED', 'STAY_BOOKED', 'TICKET_SOLD'
  ]
};