'use strict';

module.exports = {
  NOTIFICATION_TYPES: [
    'BOOKING_CONFIRMATION', // mtables, mpark
    'ORDER_UPDATE', // munch
    'RIDE_UPDATE', // mtxi
    'EVENT_UPDATE', // mevents
    'PARKING_CONFIRMATION', // mpark
    'PARKING_CANCELLATION', // mpark
    'PARKING_UPCOMING', // mpark
    'PARKING_CHECK_IN', // mpark
    'PAYMENT_CONFIRMATION',
    'WALLET_UPDATE',
    'FRIEND_REQUEST',
    'EVENT_INVITE', // mevents
    'SUPPORT_RESPONSE',
    'MERCHANT_BOOKING_UPDATE', // mtables, mpark
    'GROUP_CHAT_MESSAGE', // all services
    'SOCIAL_MEDIA_POST', // all services
    'EVENT_LIVE_UPDATE' // mevents
  ],
  DELIVERY_METHODS: ['PUSH', 'SMS', 'EMAIL', 'WHATSAPP', 'TELEGRAM'],
  PRIORITY_LEVELS: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'],
  NOTIFICATION_SETTINGS: {
    MAX_NOTIFICATIONS_PER_HOUR: 20,
    RETRY_ATTEMPTS: 5,
    RETRY_INTERVAL_SECONDS: 30,
    DATA_RETENTION_DAYS: 180,
    AI_PERSONALIZATION: true,
    BATCH_NOTIFICATION_LIMIT: 10
  },
  ERROR_CODES: [
    'NOTIFICATION_DELIVERY_FAILED',
    'INVALID_NOTIFICATION_TYPE',
    'RATE_LIMIT_EXCEEDED',
    'INVALID_DELIVERY_METHOD'
  ],
  SUCCESS_MESSAGES: ['NOTIFICATION_SENT', 'NOTIFICATION_BATCH_SENT']
};