'use strict';

module.exports = {
  REVIEW_SETTINGS: {
    RATING_MIN_INT: 1,
    RATING_MAX_INT: 5,
    DEFAULT_STATUS_TYPE: 'pending',
    ALLOWED_INTERACTION_TYPES: ['upvote', 'comment'],
    MAX_PHOTOS: 5,
    MAX_TITLE_LENGTH: 100,
    MAX_COMMENT_LENGTH: 1000,
  },
  ERROR_CODES: [
    'INVALID_CUSTOMER', 'ORDER_NOT_FOUND', 'BOOKING_NOT_FOUND', 'RIDE_NOT_FOUND',
    'INVALID_SERVICE_TYPE', 'INVALID_ORDER_STATUS', 'INVALID_BOOKING_STATUS',
    'INVALID_RIDE_STATUS', 'INVALID_RATING', 'REVIEW_ALREADY_SUBMITTED',
    'REVIEW_SUBMISSION_FAILED', 'REVIEW_NOT_FOUND', 'REVIEW_NOT_APPROVED',
    'INVALID_ACTION', 'ALREADY_UPVOTED', 'COMMENT_REQUIRED',
    'REVIEW_INTERACTION_FAILED', 'UNAUTHORIZED', 'REVIEW_NOT_EDITABLE',
    'INVALID_PHOTOS'
  ],
};