'use strict';

module.exports = {
  REVIEW_SETTINGS: {
    RATING_MIN_INT: 1,
    RATING_MAX_INT: 5,
    DEFAULT_STATUS_TYPE: 'PENDING',
    ALLOWED_INTERACTION_TYPES: ['UPVOTE', 'COMMENT', 'SHARE'],
    MAX_PHOTOS: 10,
    MAX_VIDEO_DURATION_SECONDS: 30,
    MAX_TITLE_LENGTH: 150,
    MAX_COMMENT_LENGTH: 2000,
    SOCIAL_SHARING_PLATFORMS: ['facebook', 'instagram', 'whatsapp', 'x', 'telegram']
  },
  ERROR_CODES: [
    'INVALID_CUSTOMER',
    'ORDER_NOT_FOUND',
    'BOOKING_NOT_FOUND',
    'RIDE_NOT_FOUND',
    'EVENT_NOT_FOUND',
    'PARKING_NOT_FOUND',
    'STAY_NOT_FOUND',
    'TICKET_NOT_FOUND',
    'INVALID_SERVICE_TYPE',
    'INVALID_ORDER_STATUS',
    'INVALID_BOOKING_STATUS',
    'INVALID_RIDE_STATUS',
    'INVALID_EVENT_STATUS',
    'INVALID_PARKING_STATUS',
    'INVALID_STAY_STATUS',
    'INVALID_TICKET_STATUS',
    'INVALID_RATING',
    'REVIEW_ALREADY_SUBMITTED',
    'REVIEW_SUBMISSION_FAILED',
    'REVIEW_NOT_FOUND',
    'REVIEW_NOT_APPROVED',
    'INVALID_ACTION',
    'ALREADY_UPVOTED',
    'COMMENT_REQUIRED',
    'REVIEW_INTERACTION_FAILED',
    'UNAUTHORIZED',
    'REVIEW_NOT_EDITABLE',
    'INVALID_PHOTOS',
    'INVALID_VIDEO'
  ],
  SUCCESS_MESSAGES: [
    'REVIEW_SUBMITTED',
    'REVIEW_UPDATED',
    'REVIEW_INTERACTION_COMPLETED',
    'REVIEW_SHARED',
    'STAY_REVIEW_SUBMITTED',
    'TICKET_REVIEW_SUBMITTED'
  ]
};