'use strict';

module.exports = {
  SECURITY_CONSTANTS: {
    ROLES: {
      ADMIN: {
        MFA_METHODS: ['EMAIL', 'AUTH_APP', 'BIOMETRIC'],
        TOKEN_EXPIRY_MINUTES: 15,
        ENCRYPTION_ALGORITHM: 'AES-256-GCM',
        SALT_ROUNDS: 12,
        MAX_ACTIVE_TOKENS: 5,
        ERROR_CODES: {
          SECURITY_INCIDENT: 'SEC_001',
          INVALID_MFA_METHOD: 'SEC_002',
          TOKEN_LIMIT_EXCEEDED: 'SEC_003'
        }
      },
      CUSTOMER: {
        MFA_METHODS: ['SMS', 'EMAIL', 'AUTH_APP', 'BIOMETRIC'],
        TOKEN_EXPIRY_MINUTES: 60,
        ENCRYPTION_ALGORITHM: 'AES-256-GCM',
        SALT_ROUNDS: 10,
        MAX_ACTIVE_TOKENS: 5,
        ERROR_CODES: {
          SECURITY_INCIDENT: 'SEC_001',
          INVALID_MFA_METHOD: 'SEC_002',
          TOKEN_LIMIT_EXCEEDED: 'SEC_003'
        }
      },
      MERCHANT: {
        MFA_METHODS: ['EMAIL', 'SMS', 'AUTH_APP', 'BIOMETRIC'],
        TOKEN_EXPIRY_MINUTES: 15,
        ENCRYPTION_ALGORITHM: 'AES-256-GCM',
        SALT_ROUNDS: 12,
        MAX_ACTIVE_TOKENS: 3,
        ERROR_CODES: {
          SECURITY_INCIDENT: 'SEC_001',
          INVALID_MFA_METHOD: 'SEC_002',
          TOKEN_LIMIT_EXCEEDED: 'SEC_003'
        }
      },
      STAFF: {
        MFA_METHODS: ['EMAIL', 'AUTH_APP', 'BIOMETRIC'],
        TOKEN_EXPIRY_MINUTES: 15,
        ENCRYPTION_ALGORITHM: 'AES-256-GCM',
        SALT_ROUNDS: 12,
        MAX_ACTIVE_TOKENS: 3,
        ERROR_CODES: {
          SECURITY_INCIDENT: 'SEC_001',
          INVALID_MFA_METHOD: 'SEC_002',
          TOKEN_LIMIT_EXCEEDED: 'SEC_003'
        }
      }
    },
    ENCRYPTION_KEY_LENGTH: 32,
    IV_LENGTH: 12,
    AUDIT_LOGGING: {
      SECURITY_EVENTS: ['LOGIN_ATTEMPT', 'MFA_ATTEMPT', 'TOKEN_REFRESH', 'SESSION_TERMINATION', 'KYC_VERIFICATION'],
      RETENTION_DAYS: 365
    }
  }
};