'use strict';

module.exports = {
  PARKING_BOOKING_CREATED: 'PARKING_BOOKING_CREATED',
  PARKING_BOOKING_CANCELLED: 'PARKING_BOOKING_CANCELLED',
  PARKING_TIME_EXTENDED: 'PARKING_TIME_EXTENDED',
  PARKING_CHECKED_IN: 'PARKING_CHECKED_IN',
  PARKING_SUBSCRIPTION_MANAGED: 'PARKING_SUBSCRIPTION_MANAGED',
};