'use strict';

module.exports = {
  RIDE_REQUESTED: 'RIDE_REQUESTED',
  RIDE_UPDATED: 'RIDE_UPDATED',
  RIDE_CANCELLED: 'RIDE_CANCELLED',
  FRIEND_INVITED: 'FRIEND_INVITED',
  FEEDBACK_SUBMITTED: 'FEEDBACK_SUBMITTED',
};