'use strict';

module.exports = {
  SUBSCRIPTION_ENROLLED: 'SUBSCRIPTION_ENROLLED',
  SUBSCRIPTION_UPGRADED: 'SUBSCRIPTION_UPGRADED',
  SUBSCRIPTION_DOWNGRADED: 'SUBSCRIPTION_DOWNGRADED',
  SUBSCRIPTION_CANCELED: 'SUBSCRIPTION_CANCELED',
};