'use strict';

module.exports = {
  SUPPORTED_PAYOUT_METHODS: ['bank_transfer', 'mobile_money', 'wallet_transfer', 'crypto'],
  SUPPORTED_FREQUENCIES: ['daily', 'weekly', 'biweekly', 'monthly'],
  WALLET_SETTINGS: {
    MIN_PAYOUT_AMOUNT: 5,
    MAX_PAYOUT_AMOUNT: 10000,
    PAYOUT_PROCESSING_TIME_HOURS: 24,
    AUTO_PAYOUT_THRESHOLD: 100,
    CRYPTO_WALLETS: ['BTC', 'ETH', 'USDT']
  },
  NOTIFICATION_TYPES: [
    'PAYOUT_REQUESTED',
    'PAYOUT_SCHEDULED',
    'PAYOUT_COMPLETED',
    'PAYOUT_FAILED',
    'AUTO_PAYOUT_TRIGGERED'
  ],
  AUDIT_TYPES: [
    'REQUEST_PAYOUT',
    'GET_PAYOUT_HISTORY',
    'VERIFY_PAYOUT_METHOD',
    'SCHEDULE_RECURRING_PAYOUT',
    'AUTO_PAYOUT_PROCESSED'
  ],
  EVENT_TYPES: [
    'PAYOUT_REQUESTED',
    'PAYOUT_SCHEDULED',
    'PAYOUT_COMPLETED',
    'PAYOUT_HISTORY_RETRIEVED',
    'PAYOUT_METHOD_VERIFIED',
    'AUTO_PAYOUT_PROCESSED'
  ],
  ERROR_CODES: [
    'INVALID_PAYOUT_METHOD',
    'INVALID_PAYOUT_AMOUNT',
    'INSUFFICIENT_FUNDS',
    'WITHDRAWAL_ATTEMPTS_EXCEEDED',
    'PAYOUT_FAILED',
    'KYC_NOT_COMPLETED'
  ],
  SUCCESS_MESSAGES: [
    'PAYOUT_REQUESTED',
    'PAYOUT_SCHEDULED',
    'PAYOUT_COMPLETED',
    'PAYOUT_METHOD_VERIFIED',
    'AUTO_PAYOUT_PROCESSED'
  ]
};