'use strict';

module.exports = {
  ROUTE_OPTIMIZATION: {
    FUEL_EFFICIENCY_WEIGHT: 0.35,
    TIME_EFFICIENCY_WEIGHT: 0.55,
    ENVIRONMENTAL_IMPACT_WEIGHT: 0.10,
    AVERAGE_SPEED_KMH: { urban: 30, suburban: 50, highway: 80 },
    MAX_DEVIATION_PERCENTAGE: 20,
    BATCH_DELIVERY_WEIGHT: 0.25,
    SHARED_RIDE_WEIGHT: 0.30,
    AI_OPTIMIZATION_MODELS: ['predictive_traffic', 'real_time_adjustment', 'eco_friendly'],
    MAX_WAYPOINTS: 10,
    REAL_TIME_TRACKING: true
  },
  TRAFFIC_MODELS: ['best_guess', 'optimistic', 'pessimistic', 'historical'],
  NOTIFICATION_TYPES: [
    'ROUTE_CALCULATED',
    'ROUTE_UPDATED',
    'TRAFFIC_ALERT',
    'ROUTE_OPTIMIZATION_COMPLETED',
    'ECO_ROUTE_SUGGESTED'
  ],
  AUDIT_TYPES: [
    'CALCULATE_ROUTE',
    'UPDATE_ROUTE',
    'GET_ROUTE_DETAILS',
    'TRAFFIC_ALERT_ISSUED',
    'ECO_ROUTE_APPLIED'
  ],
  EVENT_TYPES: [
    'ROUTE_CALCULATED',
    'ROUTE_UPDATED',
    'ROUTE_DETAILS_RETRIEVED',
    'TRAFFIC_ALERT_SENT',
    'ECO_ROUTE_SELECTED'
  ],
  ERROR_CODES: [
    'INVALID_LOCATION',
    'ROUTE_NOT_FOUND',
    'ROUTE_NOT_ASSIGNED',
    'MAX_WAYPOINTS_EXCEEDED',
    'NO_ACTIVE_ROUTE',
    'ROUTE_OPERATION_FAILED',
    'TRAFFIC_DATA_UNAVAILABLE'
  ],
  SUCCESS_MESSAGES: [
    'ROUTE_CALCULATED',
    'ROUTE_UPDATED',
    'ROUTE_DETAILS_RETRIEVED',
    'TRAFFIC_ALERT_SENT',
    'ECO_ROUTE_APPLIED'
  ]
};